telegram:
  bot:
    username: ${BOT_NAME}
    token: ${BOT_TOKEN}
    notify:
      delay:
        value: ${NOTIFICATION_DELAY:10}
        unit: ${NOTIFICATION_DELAY_UNIT:MINUTES} # (MINUTES / HOURS / SECONDS)

binance:
  api:
    getPrice: ${BINANCE_API_URL:https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT}

spring:
  profiles:
    active: dev
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379

  jpa:
    generate-ddl: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/currency_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      schema: currency_schema
      connection-timeout: 10000
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS currency_schema