telegram:
  bot:
#    не вписывайте данные, так как можете отправить в публичный репозиторий
#    используйте переменные среды для установки значений
#    username: ${BOT_NAME}
#    token: ${BOT_TOKEN}

    username: "@CryptocurrencyAnalyzer_bot"
    token: "6934013338:AAGE5SgRQ7-n4_tTFq36sSkss3XQsLdZie4"
    notify:
      delay:
        value: 10
        unit: MINUTES

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT

app:
  notification:
    ttl: 10 # in minutes

spring:
  profiles:
    active: dev
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/currency_db
    username: postgres
    password: postgres
    hikari:
      schema: currency_schema
      connection-timeout: 10000
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS currency_schema