services:
  postgres:
    image: postgres:12.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=currency_db

  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"

  bot:
    image: crypto-bot:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres

    environment:
      BOT_NAME: default
      BOT_TOKEN: default
      NOTIFICATION_DELAY: 10
      NOTIFICATION_DELAY_UNIT: MINUTES
      BINANCE_API_URL: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT
      POSTGRES_URL: jdbc:postgresql://postgres:5432/currency_db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: redis